 vzlist
  wget -P /etc/yum.repos.d/ http://repo.cloudlinux.com/vzlve/vzlve.repo


   yum install lve-kernel-module

  modprobe --help
   yum install vzkernel-devel
   modprobe -l  | grep lve

  modprobe lve
----------
 modprobe kmodlve
   modprobe -l  | grep lve
  vzlist
  vzctl restart 1619

===================
https://cloudlinux.zendesk.com/hc/en-us/requests/67152

Python application is not working on the cPanel server, it gives below error:

```
Unexpected issue(s) happened during importing python applications. Everything will work as before, but you won't be able to control listed applications from Python Selector UI. Please, ask you hoster to contact CloudLinux support to investigate and resolve this issue. Also you can hide this warning by deleting `~/.cl.selector/.py.migration.status` file.
```


- The second issue was related to the absent "/home/parcours/virtualenv/public_html/src/" directory, so I have created it manually:

# mkdir -p /home/parcours/virtualenv/public_html/src
# chown -R parcours:parcours /home/parcours/virtualenv/public_html
# cp -rp /home/parcours/virtualenv/public__html_src/3.5 /home/parcours/virtualenv/public_html/src/

=====================
https://cloudlinux.zendesk.com/hc/en-us/requests/67389?page=1


I've marked them with red arrows. For more information refer here:
https://docs.cloudlinux.com/cloudlinux_os_components/#installation-and-update-4

Then according to the article:
https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:cloudlinux:enable_ruby_python_selector

I've performed the command:

/usr/local/lsws/admin/misc/enable_ruby_python_selector.sh

and it installed the following packages:

    alt-ruby18-rubygem-lsapi
    alt-ruby19-rubygem-lsapi
    alt-ruby20-rubygem-lsapi
    alt-ruby21-rubygem-lsapi
    alt-ruby22-rubygem-lsapi
    alt-python33-wsgi-lsapi
    alt-python35-wsgi-lsapi
    alt-python35-wsgi-lsapi

also the same command during execution built and installed a package wsgi-lsapi-1.4 from LiteSpeed repositories:

After that I performed the last set of commands:

root@guy [~]# su -s /bin/sh ntpmbca
sh-4.1$ rm ~/.cl.selector/.py.migration.status
sh-4.1$ ls -la ~/.cl.selector/.py.migration.status
ls: cannot access /home/ntpmbca/.cl.selector/.py.migration.status: No such file or directory
sh-4.1$

and the error is gone from the user's interface. Please check from your side and confirm that your Python Selector for this user now works as expected. You can also delete the file:

~/.cl.selector/.py.migration.status
=====================
http://www.crimeflare.org